version: 2.1 # use CircleCI 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/codio-website # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: echo env variable
          command: 'echo ${API_URL}'
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      # - run: # run tests
      #     name: npm test
      #     command: npm test
      # - store_test_results:
      #     path: ./test-results
      # - store_artifacts:
      #     path: ./test-results
      # - run: # run coverage report
      #     name: Code Coverage
      #     command: npm run coverage
      # - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      #     path: coverage
      #     prefix: coverage
      # - codecov/upload:
      #     file: ./coverage/clover.xml
      #     token: 'e50f85c6-56d5-40b7-8c2d-1a44d96cd9e8'
      - run:
          name: Install Python
          command: 'sudo apt-get update && sudo apt-get install -y python-dev'
      - run:
          name: Download pip
          command: 'sudo curl -O https://bootstrap.pypa.io/get-pip.py'
      - run:
          name: Install pip
          command: 'sudo python get-pip.py'
      - run:
          name: Upgrade aws-cli
          command: 'sudo pip install awscli --upgrade'
      - run:
          name: Check AWS
          command: 'aws --version && aws s3 ls'
      - run:
          name: Deploy
          command: 'npm run deploy'
